### ISSUE TITLE
New opening 'scene'

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#106]
* initial three seconds with no reader/reading and band in light grey
* then, the reader starts and the bands 'colors-in' (with no 'red' for the [non-current] urban domain and no purple for found words)
* then, the usual 40 sec period of no updating (pause)
* then, as before, updating starts, and the usual domain back-and-forth behavior begins.

**Comment by dhowe** [comment]
done 
@shadoof please check on branch 'open'

**Comment by shadoof** [comment]
Looks good to me and I do think if makes more sense of the opening.

**Comment by dhowe** [comment]
merged in v1.0.85
