### ISSUE TITLE
Words on reader's current line should not be replaced

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#110]
rather than simply the words being read
@shadoof do you concur?

**Comment by shadoof** [comment]
Yes I do concur. (And this should be a good solution to this likely timing-related problem of preventing changes in the [darker] word-being-read, which was still, rarely, occurring.)

**Comment by dhowe** [comment]
@shadoof pls verify and close if ok

**Comment by shadoof** [comment]
Watched and saw changes in darker highlighted lines at least twice in 1.0.88 main. Can't imagine why this is proving so hard to solve.

But I have to say, again, that this does not strike me as a big issue (changes being so well dynamically typeset) although it would be good, in the fullness, to have it working perfectly.

**Comment by dhowe** [comment]
interesting, I do see message like below in the logs:

`[SKIP] @11.152 [nns] 'quarters' is currently being read`

but there must be an edge case I am missing

**Comment by dhowe** [comment]
give this a check when you have a moment @shadoof

**Comment by shadoof** [comment]
I been reading 1.0.97 for a good half hour and have never noticed a word changing on 'the reader's line'. I think this can be closed.
