### ISSUE TITLE
Update CSS for affinity bands

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#25]
We currently have 4 bands rural, urban, rural-strict & urban-strict. The goal here is to have rural and urban moving in opposite directions: urban=clockwise, rural=anti-clockwise, both starting at 12 oclock. And also to have the strict band layered atop the non-strict.

- [x] Overlay the strict band atop the non-strict band for each domain 
- [x] Double the width of each band (total width remains the same)
- [x] Make 2 rural bands move anti-clockwise
- [x] Add constant black background circle extending from one pixel inside innermost band, to one pixel beyond the outermost band

**Comment by Real-John-Cheung** [comment]
![圖片](https://user-images.githubusercontent.com/61215358/163707324-5adcb4f9-27de-46ff-b033-99826f68b38d.png)

**Comment by dhowe** [comment]
this looks good! Can I assume all the CSS for the band colors is organized in one place ?

**Comment by Real-John-Cheung** [comment]
It is in the main.js 
https://github.com/dhowe/ramble/blob/8e911751001c49a3d332b97a8f90776029ec1f9c/main.js#L42
[colorForBackground, colorForProgressBar1, ...]
see https://github.com/dhowe/ramble/blob/8e911751001c49a3d332b97a8f90776029ec1f9c/main.js#L268 for which progress bar corresponding to which data entry

**Comment by shadoof** [comment]
Great work! But ... the black *background* for the affinity bars does not work (makes it look as if *black* might represents measures of affinity). I suggest:

- [ ] black outline of 1 (max 2) pixels immediately outside the area of progress/affinity bars (such that background for the bars is just the general background, and so the black just outlines the whole project/visualization)
- [ ] reduce width for each of the two bars (now with great overlays) to the width of the bars in the display when there were four of them (try this after first seeing what it looks like with black outline and current affinity bars width)

**Comment by Real-John-Cheung** [comment]
> black outline of 1 (max 2) pixels immediately outside the area of progress/affinity bars (such that background for the bars is just the general background, and so the black just outlines the whole project/visualization)

not sure if i get it but do you mean something like this
![圖片](https://user-images.githubusercontent.com/61215358/163726071-06d7958e-1910-48d7-92a0-6cb22212cc2d.png)

with old stroke width
![圖片](https://user-images.githubusercontent.com/61215358/163726160-085c9e3f-c145-468d-84cb-6c10096cfc28.png)

**Comment by shadoof** [comment]
Yes. This is what I meant. Thanks!
Daniel: What do you think? I think the second image above with 'old stroke width' looks best?

**Comment by dhowe** [comment]
Looks good to me. However I think the width of the bands needs to be proportional to the text-size (if its not already), and should be ~1 pixel at the size above (it looks a bit more than that)

**Comment by shadoof** [comment]
+1 to Daniel's comment on width of bands. Makes sense.

**Comment by Real-John-Cheung** [comment]
> the width of the bands needs to be proportional to the text-size 

The band width is related to text-size in someway: The whole circular display will try to take over the whole window, the band width is proportional to the window width and so as the text size
with #27 the outermost background band should be around 1 px wide in a 1920*1080 window (and wider in a bigger resolution window&screen)
<img width="1052" alt="螢幕截圖 2022-04-18 下午3 09 52" src="https://user-images.githubusercontent.com/61215358/163770483-1d914fb5-da33-43a4-a056-898d7ec1ea7d.png">
![image](https://user-images.githubusercontent.com/61215358/163770643-2887e878-5871-4483-be34-b00266a7ade4.png)

**Comment by shadoof** [comment]
I've been watching and thinking about the affinity bands. I now think that they should _operate_ as they do, **but**:

- [ ] The bars for rural and urban must have contrasting color shades (just go for rural: greenish; urban: reddish)
- [ ] Daniel suggests rural should go clockwise from top; and urban should go anti-clockwise from top. This is up to Daniel.
- [ ] I strongly think, however, that both of the _strict_ affinity bars should be in the same 'outer' (larger diameter) track of the two; and that both of the non-strict affinity bars should operate in the same 'inner' track of the two tracks.

This will have these effects: the outer – strict – track will have a small but varying white-space gap between the moving ends of the two strict bars (the gap will only disappear when one or other urban or rural state is fully reached). The inner - non-strict - bars will overlap: but this is also as it should be since it will show how, non-strictly, the two texts share a great deal in word-percentage terms.

**Comment by dhowe** [comment]
> The inner - non-strict - bars will overlap

In this case the 'current' text (rural or urban) is drawn _over_ the other ?

**Comment by shadoof** [comment]
Yes. With careful color-choice + opacity, I think this will work. 
The current version is hard to read anyway. In this arrangement, the inner (nearer the text) non-strict will not have any gaps but the overlapping area will change size and move. The outer (between non-strict and the extreme outer black outline) band will have a gap of varying size that will also move but overall giving, I think, a very clear indication of which text is prevalent.

**Comment by dhowe** [comment]
@Real-John-Cheung pls implement (and add a check) when you have a moment:
- [x] The bars should have contrasting color shades (rural: greenish; urban: reddish)
- [ ] Rural should go clockwise from top; and urban should go anti-clockwise from top
- [ ] Both strict affinity bars should be in the same 'outer' (larger diameter) track of the two; and both non-strict affinity bars should be in the same 'inner' track

**Comment by dhowe** [comment]
these are good - I prefer 1) blue/red 2) blue/yellow...

**Comment by shadoof** [comment]
Functioning as envisaged. Thanks! I prefer blue/red.
