### ISSUE TITLE
Implement looping protocol

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#29]
start domain: rural

LOOP:
```
1. X seconds with no actual walking in or out (X: preUpdateDelay)
2. start updating
3. Y legs in current domain (Y: shortWalkLength)
4. on return from the last inward leg, switch domains
5. Z legs (Z: longWalkLength) in order to render the text more or less in the new domain
6. on return from the last inward leg, switch domains
7. stop updating
```
@shadoof please check/verify spec above

**Comment by shadoof** [comment]
Yes, I think this spec is should work.

**Comment by dhowe** [comment]
@shadoof pls add a line about the wholesale text update which (I believe) happens between step 6 and 7

**Comment by shadoof** [comment]
revised (and simpler) loop:

```
domain = rural
no word updates for delay = time of 3 legs
do 4 legs // 2 x out and in
while (true) {
    switch domain
    do 20 legs
    no word updates for delay = time of 3 legs
    do 4 legs
}
```

**Comment by dhowe** [comment]
and is the above the same as:
```
dest=rural
while (true) {
    no word updates for delay = time of 3 legs
    do 4 legs
    switch domain
    do 20 legs
}
```

**Comment by shadoof** [comment]
My bad on domain. I mean `destination`

And yes, my loop is equivalent of your better, simpler loop code.

The unpacked loop looks fine above but I'm not sure I've seen this yet in the published version ..

Am I right in realizing that for you a leg = one out-going jaunt + on in-coming jaunt ?

**Comment by dhowe** [comment]
ok, so I've changed the code to use `domain` as this seems more intuitive
previously a `leg` has meant a return trip: one outgoing + one incoming, but this can be changed 
so you are seeing 8 and 40 legs (by your new definition)

with all that said I need to verify (tomorrow) that this is actually what's happening

**Comment by dhowe** [comment]
@shadoof please verify and close if ok

**Comment by shadoof** [comment]
looping working well and parameters give the ability to adjust as necessary. I have done some adjusting locally and offered this as a pull request from my repo on the main branch because I don't think they are controversial. Hope this is OK.
