### ISSUE TITLE
words with length < 4 && which have composed alternates in the corresponding texts should be allowed to change

### ISSUE THREAD

**Issue by shadoof** [dhowe/ramble#33]
This is very much an edge case thing. The example that prompted the issue is 'dip' - rural - for which I substituted 'prayer' in urban. Because we set off in rural, it never changes.

There are only four such words in rural: set, dip, the, its. In the urban text there are two occurrences of "our" which are different words in rural.

Can we handle this? Perhaps allow such a word to change, but only to its correspondent in the other text?

Assigning this to your because you have the best handle on how the length and stop word tests are currently dealt with.

**Comment by dhowe** [comment]
done
