### ISSUE TITLE
Words changing while being 'read'

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#35]
> from@shadoof
> only noticeable when the line is long
> minor issue

this is occurring b/c we check that the word is not being reader _before_ it is sent to the worker to find similars

we can also check after the results come back from the worker but we would have to abort at that time and pick a different word to replace

**Comment by dhowe** [comment]
should be fixed @shadoof can you check for this?

**Comment by shadoof** [comment]
I have not seen this since starting to watch the latest version ... and now over quite a long time, intermittently. I think it was quite a minor issue, and especially now the typography is so good. I'll close but will reopen if I see something.
