### ISSUE TITLE
Length-aware random selection

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#36]
'trite' has been added to `ignores`, and the cache regenerated, so this will not happen anymore. Note that this (either regenerating or hand-editing the cache.js file) is required whenever the `ignores` list is changed.

However, the reason this was happening remains, specifically that 'trite' was the only replacement option (for the only replaceable word, 'light') that was shorter than the current word, on a line that was often too long. So it was repeatedly selected. Current code has a check so that the same word is never chosen twice, however this could result in replacements oscillating between the two shortest (or longest) words in a similar list.

So one potential solution is to do a probabilistic random selection based on length, where shorter words have a higher chance of being picked on a long line (and vice versa), but all valid replacement words have _some_ chance of being chosen. 

This involves a bit of added complexity, and, more importantly, could occasionally result in lines that are noticeably longer or shorter than ideal. So we'd have to weigh this against how things are working now... @shadoof ?

**Comment by shadoof** [comment]
If we are always using "shortest replacement option" over other "short-enough" options, then I think this is a problem. Could we find all options that are "short-enough" and select from them randomly (also retaining the don't pick the same alternate twice)?

The length-of-word stricture clearly has more effect when the line is short (at the top and bottom of a circular layout) and we have to live with that. "light" appears three times: close to top, close to bottom, and on a much longer line towards the bottom. I think if the "short-enough" parameter can be calculated we should use this and then watch what happens to the middle occurrence of "light" on the longer line. So long as it displays a number of variants, we're good, and we haven't risked too many noticeably longer lines.

**Comment by dhowe** [comment]
It is indeed randomly selecting, on a line that is too long, from ALL words shorter than the current word. The problem in this case is that 'trite' was the only word shorter than light, given the current set of css options:

```
Processing 'light' (32px), looking for a shorter word: 
...
bright=42.07603219207763
contrite=54.06845353271484
forthright=67.7469713623352
outright=56.73428536624145
overnight=66.30391811462403
polite=39.62285446884155
right=33.4253797951355
tight=32.954487878082276
upright=51.281111712982174
uptight=50.81021979592895
white=38.96969757247925
trite=29.468405465515136

selected:  'trite'
```

**Comment by shadoof** [comment]
I'm afraid that I think we need the different algorithm not just cause it would provide more variation but also because I think the current algorithm prevents 'strict' words (those that differ in the composed texts) that have changed from one domain to the other from going back to the the 'origin' word of their original domain. (E.g. "inhuman" rural, changes to "military" urban, and then rarely if ever gets back to "inhuman")

**Comment by dhowe** [comment]
implemented
