### ISSUE TITLE
Optional strict bars (branch=fix38)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#39]
branch: 'fix38', file: main.js
need a boolean `displayStrict` that will show and hide the strict (outer) progress bars
for now, when the strict progress bars are hidden, the regular (inner) bars should be double the current width

**Comment by Real-John-Cheung** [comment]
when the strict bars are hidden:
![圖片](https://user-images.githubusercontent.com/61215358/166140326-f4ba0052-4196-49dc-8520-03a6994f5e7d.png)

**Comment by dhowe** [comment]
looks good! a couple of tweaks:
- [ ] remove black outer line when strict is hidden
- [ ] add one more legend-color (purple) called 'overlap'

**Comment by Real-John-Cheung** [comment]
![圖片](https://user-images.githubusercontent.com/61215358/166142664-d6e720f0-8591-475d-bcb8-11faacf860a4.png)
![圖片](https://user-images.githubusercontent.com/61215358/166142728-86ab4de3-2eba-4f07-aae1-1dfbcddd2084.png)

**Comment by dhowe** [comment]
@Real-John-Cheung Did you make these changes in the 'fix38' branch? The PR targets the 'main' branch...

**Comment by Real-John-Cheung** [comment]
hmm I can't find the 'fix38' branch in the repo
![圖片](https://user-images.githubusercontent.com/61215358/166156546-0cfd9f42-d794-452c-8c03-c0263767b976.png)

**Comment by shadoof** [comment]
Please read my extended note in the README.md of this branch.
