### ISSUE TITLE
Implement auto-hiding (top-of-page) legend

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#48]
add a boolean flag `hidingLegend` which, when true, shows the legend as a hover-only bar which appears at top-left
should work something like this:  https://thelaob.com/a0/utopianplatform/
showing the 4 legend items horizontally
(and should be responsive)

when false, should work as is (pls check that it is responsive)

**Comment by Real-John-Cheung** [comment]
Should this be made in the main branch?

**Comment by dhowe** [comment]
pls use 'newviz' - but I will merge this to main shortly...

**Comment by dhowe** [comment]
Looks quite good -- I don't think we need it to the left. 
A few adjustments:

- [ ] Should be top margin above text-circle equal to the size of the hover-legend (so they don't overlap)
- [ ] Legend should be horizontally-centered over the text-circle
- [ ] Vertically align legend text
- [ ] Cursor should be 'none' when inside the text-circle's outside band edge
- [ ] White transparent rectangle should extend to full width of page
- [ ] Original legend needs to placed correctly when showing (see image below)

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/737638/166867075-cf75bde4-acec-45ca-8581-2c5a099af64b.png">

**Comment by dhowe** [comment]
![image](https://user-images.githubusercontent.com/737638/167129722-8c547788-30b6-44e3-b022-4d4baafbb206.png)

**Comment by dhowe** [comment]
Seems we should also have an about overlay (title, author, year, desc, etc.) - will create a separate ticket
