### ISSUE TITLE
Incorrect POS in sources

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#5]
index 125, 'fish' and 'neighbors' listed as 'nn'
should be 'nns' 
please confirm and I will make the fix

**Comment by shadoof** [comment]
You prob already fixed this but, yes: confirmed!


On November 11, 2021 at 6:35:52 AM, Daniel Howe ***@***.***) wrote:

index 125, 'fish' and 'neighbors' listed as 'nn'
should be 'nns'
please confirm and I will make the fix

**Comment by dhowe** [comment]
done
