### ISSUE TITLE
Updates to various measurement calculations

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#54]
- [x]  uniform/accurate way to measure `scaleRatio` ( currentRadius/initialRadius ?) 
- [x]  uniform/accurate way to measure `width` of a line, given its index (with scaleRatio, word-spacing taken into account)
- [x]  uniform/accurate way to measure `width` of a line with one substituted word
- [x]  notate which computations happen at current-scale, and which happen at scale=1

the top three should probably be their own functions: 

- `getScaleRatio()`
- `getLineWidth(lineIdx)`
- `getLineWidthAfterSub(newWord, wordIdx, lineIdx)`

**Comment by Real-John-Cheung** [comment]
I realize a thing: the value inside `initMetrics.lineWidths` are the width of the designed bound box, i.e. the "max width" for the initial lines, but not the actual width of the text, so even before any substitution, the result of `getLineWidth()` will not always be the same of  `initMetrics.lineWidths`, I put the values of the actual width of text for each line before any substitution in `initMetrics.contentWidths`
