### ISSUE TITLE
Vertical alignment in iframe

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#58]
So this problem exists only inside the iframe, on the pre-publication page that we need to approve. As best I can tell the text content of the piece is not vertically aligned correctly. When compared to the src for that iframe (https://rednoise.org/preoccupations/), it is noticeably higher. Thoughts?

**Comment by dhowe** [comment]
<img width="809" alt="Screenshot 2022-05-13 at 1 34 13 AM" src="https://user-images.githubusercontent.com/737638/168135937-3bdbdb0a-4d16-4543-8c46-d5890ab7b305.png">

**Comment by Real-John-Cheung** [comment]
#61 should fix the layout issues 
![圖片](https://user-images.githubusercontent.com/61215358/168416794-32bc6874-a453-447f-b3fd-dd4c53a54e93.png)
![圖片](https://user-images.githubusercontent.com/61215358/168416903-e948c57b-2a6d-4771-a403-d51fdaf0e441.png)

**Comment by dhowe** [comment]
interesting that you are seeing this font (I think we need to load the correct one)
