### ISSUE TITLE
Don't allow words read (by reader) to be replaced

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#6]
Don't allow words, as they are being read (by reader) to be replaced - @shadoof what do you think about this?

might also allow the reader to reset the color back to default?

**Comment by shadoof** [comment]
I very definitely agree that word being read by reader should not be replaced. (And I'd be happy for you to be the one to code this ;)

I'm assuming that, on publication, words that are being replaced will not be colored, that this will not be part of whatever affinity visualization that we do implement.

**Comment by dhowe** [comment]
done
