### ISSUE TITLE
Getting line width

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/ramble#66]
@dhowe 

Refer to the previous discussion, I think now there is two issues with the measurement:

- [ ] 1. how to add word spacing to the measurement with canvas context
- [ ] 2. the difference between getting the line width using canvas context and using `getClientBoundingRect` (pls see my comment below)

**Comment by Real-John-Cheung** [comment]
so for the difference between getting the line width using canvas context and using getClientBoundRect, here is a graph 
<img width="951" alt="螢幕截圖 2022-05-16 下午2 35 40" src="https://user-images.githubusercontent.com/61215358/168535899-225f8718-41d7-4089-af55-fcf2f1514bed.png">
The upper text is rendered in a  `span` element and the lower one is rendered on canvas, with same font attribute.
The blue rectangle represents the width got from `measureText().width`, and the red one represents the width calculated from `measureText().actualBoundingBoxLeft and measureText().actualBoundingBoxRight`. The dotted line represents width from `getClientBoundRect`, as shown in the graph, it somehow falls between the middle of the above ones.

**Comment by dhowe** [comment]
we don't need perfect accuracy for our case, only
- [ ] accuracy within ~2 pixels at font=20px
- [ ] consistent across all browsers (not between browsers)
- [ ] must to be fast *

**Comment by Real-John-Cheung** [comment]
Some notes:

1. bugs occasionally occurs in Safari (Mac) now, will look into that later. 
2. all functions related to measuring width is moved to helper.js
3. add two width change percentage function, one with canvas context and one with dom, the dom one is much more slower as expected, and the accuracy are similar between the two (see line 151 - 163, main.js)
4. the function accept a field option (line 153 & line 160, main.js) the default is `['max','min']` which means the functions will return the results with max and min word spacing, there is also a field call `opt` which means the functions will also try to do the word space adjustment and return the optimised width and word spacing, but it make it much more slower (more details in line 117 - 126, helper.js)

**Comment by dhowe** [comment]
Thanks for this -- a few questions:
- [ ] word-space adjustment, different values computed in `adjustWordSpace()` and `estWidthChangePercentage()`
- [ ] in the current layout, we get no words on the initial line, which is a change -- actually it looks better, but its not how the algorithm _should_ work

**Comment by dhowe** [comment]
- [ ] optimal solution doesn't not get close enough to target (?) - see below

CASE:

minAllowed=642.9258462843284 
target=676.7640487203457 
current=667.7832641601562 
maxAllowed=710.6022511563631

Optimal:
max: [0.5548724641895738, 680.5192260742294]
min: [-17.885823408469438, 555.7192260742166]
opt: [0.5518106190086502, 680.5192260742188, 10.4]

Post-adjustment:
wordspace: 0.500 
adjustedWidth: 680.519 (note: this is 4 pixels from optimal)

**Comment by Real-John-Cheung** [comment]
>  optimal solution doesn't always seem to get close enough to target?
Ah this is caused by a mistake in the code, which makes the function always return the bigger estimate instead of the better one between the bigger estimate and smaller estimate. I will include the fix in next PR

**Comment by Real-John-Cheung** [comment]
> in the current layout, we get no words on the initial line, which is a change -- actually it looks better, but its not how the algorithm should work 

I am not sure if i understand this correctly, but we do have words in the first line:
![圖片](https://user-images.githubusercontent.com/61215358/169235949-ad998713-19d5-456f-92b8-6938b2dd8e04.png)

**Comment by dhowe** [comment]
I guess it is only the last line that is empty, which is fine...

**Comment by Real-John-Cheung** [comment]
I made some change on the `adjustWordSpace`, it now will try to get as close to target as possible instead of stopping in a range, just like the est function, now the output should be the same (the 4th number in the opt array is wordspacing in em)
![圖片](https://user-images.githubusercontent.com/61215358/169242242-c2e370ab-980b-4e28-9aa9-4b14833494bf.png)

**Comment by Real-John-Cheung** [comment]
![圖片](https://user-images.githubusercontent.com/61215358/169272502-bbe05d49-a4c2-42f6-a58d-9c95f16a868a.png)
should be fixed now
