### ISSUE TITLE
The problem of might; or the commutativity of similarity

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#76]
There is a problem with 'might', which occurs in the original text, where it leads to a single similar and then oscillates. I've added a few additional similars to the overrides (would, could, should, must), but I notice that we are often then stuck on one of these. 

So the question is whether we should consider similar-words to be sort of commutative, so that if word `A` has similars `[B,C,D]`, then word `B` should have, at least, `[C,D,A]` for similars, etc.

If not clear, just check [this line](https://github.com/dhowe/ramble/blob/main/main.js#L47)

So one option is to automatically do exactly what is written there (the 4 subsequent lines) for _every_ similar-override...

**Comment by dhowe** [comment]
this is implemented (you can see result in first few lines of console output):

```
[INFO] Ramble v1.0.65
[INFO] Found 17 similar overrides, 142 entries
[INFO] Loaded 176 cached similars, 303 total entries
```

@shadoof please close if you agree, else respond below

**Comment by dhowe** [comment]
Another question, @shadoof, is whether we want to do this for newly discovered words. For example, we lookup a new word at runtime `A` and find similars `[B,C,D]`, and `A` is added to our cache, in case it comes up again. Do we also want to add the following to the cache, if they are not there? Or perhaps we use them only if we get no other results via a normal RiTa-based search?

```js
{
  B: [C,D,A],
  C: [B,D,A],
  D: [B,C,A],
}
```

FYI, the max number of similars we accept is currently set to 20.

**Comment by shadoof** [comment]
I agree with the already implemented commutativity. 

For the second question, hard to gauge that possible effects but instinct says: implement but, "we use them only if we get no other results via the usual RiTa search?"

**Comment by dhowe** [comment]
`For the second question, hard to gauge that possible effects but instinct says: implement but, "we use them only if we get no other results via the usual RiTa search?"`

Agreed

**Comment by dhowe** [comment]
implemented
