### ISSUE TITLE
Question: ellipsis at end of text(s)

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#83]
will help with spacing of last-line, if not abhorrent to @shadoof

**Comment by shadoof** [comment]
I'm o. k. with it but not over-keen. I'd kinda prefer if there were a space between the last word and the ellipsis

**Comment by dhowe** [comment]
yes, that was my initial implementation... but when that line has larger word-spacing (which is almost always the case) the space between the last word and the ellipsis seems abnormally large.

can implement a fixed-width space post-release, or just remove, though removal augments the word-spacing issue on that line (can see if you hit the 'w' key)

**Comment by shadoof** [comment]
I'm ok with whatever you decide here.
