### ISSUE TITLE
Padding, layout different on github.io

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#84]
Not sure why this is but I'm pretty sure this is the case (and this is where we are publishing from): https://dhowe.github.io/ramble/

github:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/737638/169651551-af2246fc-c442-49aa-b8cf-72a2a431beb0.png">

local:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/737638/169651591-b086ded2-f18f-4b6d-9dc8-df17eccdafd4.png">

**Comment by Real-John-Cheung** [comment]
![圖片](https://user-images.githubusercontent.com/61215358/169651633-16873747-3145-45cb-b8a4-78259130a71c.png)
but github.io looks fine on my machine

**Comment by dhowe** [comment]
interesting -- I don't see it now either w v1.0.62...
reopen if problem comes back
