### ISSUE TITLE
Text layout in Safari (desktop) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#85]
as reported by @shadoof ...

**Comment by Real-John-Cheung** [comment]
seems to be caused by the `aspect-ratio` attribute not being supported on mobile safari...

**Comment by dhowe** [comment]
also text-layout incorrect (or at least different) on safari desktop

(need to implement no-widow/orphan rule at least)

**Comment by Real-John-Cheung** [comment]
> also text-layout incorrect (or at least different) on safari desktop 

a simple way will be making sure there's at least 2 words in a line (tho maybe not a elegant one), trying it out

**Comment by Real-John-Cheung** [comment]
> (need to implement no-widow/orphan rule at least) 

with min word num = 2 per line
<img width="940" alt="螢幕截圖 2022-05-21 下午11 51 10" src="https://user-images.githubusercontent.com/61215358/169659418-9379467d-7484-472c-979e-ecaf56ed9d78.png">

with min word num = 3  per line
<img width="940" alt="螢幕截圖 2022-05-21 下午11 50 26" src="https://user-images.githubusercontent.com/61215358/169659352-14e02a3d-f508-45ed-bb8e-0b1cf74d7e2f.png">

**Comment by Real-John-Cheung** [comment]
the `minWordNum` value is in line 186, `circular-layout.js`

**Comment by dhowe** [comment]
note: I've fixed the issue with that ellipsis being treated as a separate word...

**Comment by dhowe** [comment]
should probably be two tickets, one for desktop safari, one for ios

**Comment by dhowe** [comment]
The layout is still not quite correct on safari -- notice the difference in the line-breaks (is this a canvas measurement issue?)

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/737638/169665251-30f37e56-4f2a-4cd9-b00d-f4548ea33109.png">

**Comment by shadoof** [comment]
<img width="693" alt="Safari Desktop 2022-05-21 at 7 24 40 PM" src="https://user-images.githubusercontent.com/1051808/169672312-2d441012-1efa-4a6a-a439-8753a2cca837.png">
Yes: I am also seeing this.
Safari 15.5
MacBook Air (M1, 2020) MacOS 12.4

**Comment by Real-John-Cheung** [comment]
> is this perhaps a canvas measurement issue, or a line-height issue

Yes i think so, so the direct cause of the different layout is that the calculated font size is 20.4 px on Safari instead of 20.8px on Firefox and Chrome. Looking into why is this difference occurring

**Comment by Real-John-Cheung** [comment]
So this is caused by on safari, canvas context will round the font size to integer 

test on Safari
<img width="570" alt="螢幕截圖 2022-05-22 下午3 38 58" src="https://user-images.githubusercontent.com/61215358/169684256-6aeb8bb7-c1a2-4de4-9837-b71bbe90f1e2.png">
same page on chrome
<img width="570" alt="螢幕截圖 2022-05-22 下午3 40 10" src="https://user-images.githubusercontent.com/61215358/169684286-224e44da-0bd8-4e80-91c0-acd3835d4ac2.png">

**Comment by dhowe** [comment]
interesting, I think I may have read this... 

solution ?  hard code the line-breaks for safari only ... ?

**Comment by Real-John-Cheung** [comment]
i am trying to make some correction for the width from context for safari only (the way to do this is, computed font will === ctx font on firefox & chrome and false on safari)

**Comment by dhowe** [comment]
the layout in scale=1 is the same every time, so it can be hard-coded for all the browsers, no?

**Comment by Real-John-Cheung** [comment]
> the layout in scale=1 is the same every time, so it can be hard-coded for all the browsers, no?

in most cases, yes but not always, it might changes when the screen is huge (4k, for example)

I found a way to make the correction for safari and it should fix the layout  
<img width="923" alt="螢幕截圖 2022-05-22 下午4 30 23" src="https://user-images.githubusercontent.com/61215358/169685903-fdad7c32-cf6e-43ca-9ac7-9dd96e3d806f.png">
