### ISSUE TITLE
Test on various mobile

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#92]
- [x] Android
- [x] iOS
- [ ] Amazon Fire tablet (problem*)
- [ ] other?

**Comment by Real-John-Cheung** [comment]
tested on Ipad (Safari, Ipad OS 15)

**Comment by shadoof** [comment]
Safari iOS and desktop from Cayley's devices accessing rednoise.org on HK Sunday evening:
Layout is not the same but is acceptable, in my opinion.

![Safari iOS from rednoise - 1](https://user-images.githubusercontent.com/1051808/169698997-9f11c953-d6b5-451e-8311-a578211e7880.png)
<img width="669" alt="Safari desktop from rednoise" src="https://user-images.githubusercontent.com/1051808/169698999-60407def-fae3-4698-a896-a8dac6b48ca5.png">

**Comment by shadoof** [comment]
Does not work on a Amazon Fire Tablet using its 'Silk` browser. (It's unclear whether hacking such a tablet to be able to install Chrome would work and would be worth it.)

FYI, I am buying a (cheapish) Chromebook tablet to see if it will run recent webapp sketches including this one.

**Comment by dhowe** [comment]
android all good, though no legend (as expected)

**Comment by shadoof** [comment]
Just FYI. This is not one of the tasks and prob not an issue since Chromebits do not seem to be widely used or available any more *and* the version of the Chrome OS they implement not longer allows updates to the current version. All that made clear, *Preoccupations* would not run on the ASUS CHROMEBIT CS10 Stick-Desktop PC with RockChip 3288-C 2 GB LPDDR3L 16 GB eMMC Google Chrome OS (2016) that I have hooked up to a flatscreen at Brown.

**Comment by dhowe** [comment]
can you clarify what you mean by "won't run"

**Comment by shadoof** [comment]
Blank screen when accessing the URL. Whereas, e.g. https://shadoof.github.io/xmas (and other recent webapps) does run. I dd not have time to try and call up a console and I'm not sure that this installation of Chrome (Chrome OS) has the console easily accessible. (Usual Chrome key command did not bring it up.)

This hardware is basically running an earlier version of Chrome (that latest update that the hardware will allow, don't have details but these can be googled).

**Comment by dhowe** [comment]
would need to see the console output to debug

**Comment by dhowe** [comment]
any others we want to test, or should this be closed?

**Comment by shadoof** [comment]
enough tested, for now, I think
