### ISSUE TITLE
Test within Wordpress iframe

### ISSUE THREAD

**Issue by dhowe** [dhowe/ramble#93]
https://thenewriver.us/preoccupations/

**Comment by shadoof** [comment]
Have been looking at it on the _New River_ site using Chrome and, this is not necessarily a bug but:
- when viewing the piece on the page with the documentation, the legend cannot be made to show (by hovering at the top of the iFrame), but
- after clicking to view in 'full screen' on rednoise, the legend does work (it did *not* for me once, but does now)

I guess this is desired behavior.

I have also made a ticket, hoping that someone (might be me) will add a `meta` tag `title` to the piece as served from rednoise.

**Comment by Real-John-Cheung** [comment]
> when viewing the piece on the page with the documentation, the legend cannot be made to show (by hovering at the top of the iFrame), 

hmm but it did show on my machine, in both Chrome and Firefox
![圖片](https://user-images.githubusercontent.com/61215358/169745240-0b23f799-3249-4f4a-b0cc-c6daaec7cd9a.png)
![圖片](https://user-images.githubusercontent.com/61215358/169745269-86100643-7832-4570-a765-10491905420c.png)

**Comment by dhowe** [comment]
- [ ]  solution for revealing legend ?
- [ ]  I-key reveals 'info' panel, but it is currently too close to bottom of ring

**Comment by shadoof** [comment]
Report on the legend not appearing in iFrame was 'my bad' - sorry @Real-John-Cheung . 

But this brings up the question of the *unique* period at an opening/refresh of the piece when:
- visualization, and
- legend behavior, and
- [easter egg] (i)nfo key behavior 

... are all different. 

As a 'silent' server-side change, or for the next release, @dhowe,  I'd still suggest:
- initial three seconds with no reader/reading and band in light grey
- then, the reader starts and the bands 'colors-in' (with no 'red' for the [non-current] `urban` domain and no purple for `found` words)
- then, the usual 40 sec period of no updating (pause)
- then, as before, updating starts, and the usual domain back-and-forth behavior begins.

**Comment by dhowe** [comment]
apologies if I forgot to create a new ticket for this (I thought I did)
