### ISSUE TITLE
Add three-bar icon to top of page, visible always

### ISSUE THREAD

**Issue by shadoof** [dhowe/ramble#99]
I don't think these is a quick fix for this. next release?

And I don't think it's vital for this release.

**Comment by Real-John-Cheung** [comment]
I think a simple way is to make the right bottom legend (view this by pressing 'c') default for mobile devices
otherwise we would need to think about what interaction should be used corresponding to mouse hovering on desktop

**Comment by dhowe** [comment]
What about adding a minimal 3-bar icon for mobile (as below) which could show the title/authors/description/legend, as it does in "Radical" ? 

<img width="679" alt="image" src="https://user-images.githubusercontent.com/737638/169820556-8440e72e-b267-4fb6-9c6b-6b045dadeb24.png">

**Comment by shadoof** [comment]
See #105. I like the three-bar icon these days. 

If we ever want to capture and respond to mobile gestures, I have used `hammer.js`.

**Comment by dhowe** [comment]
three-bar icon: something like at https://rednoise.org/rotvh/
